// react-hereoes/src/views/Dashboard.tsx
import { useSelector } from "react-redux";
import DashboardHero from "../components/DashboardHero";
import { AppStateModel } from "../store";

export default function () {
  const hereos = useSelector((s: AppStateModel) => {
    const { heroes, topHeroes } = s.heroes;
    const heroSet = new Set(topHeroes);
    return heroes.filter((hero) => heroSet.has(hero.id));
  });

  return (
    <>
      <h2>Top Heroes</h2>
      <div className="dashboard-heroes">
        {hereos.map((hero) => (
          <DashboardHero {...{ hero, key: hero.id }} />
        ))}
      </div>
    </>
  );
}

// svelte-heroes/src/pages/Dashboard/Dashboard.svelte
<script lang="ts">
  import { Link, link } from "svelte-navigator";
  import DashboardHero from "./DashboardHero.svelte";
  import heroesStore from "../../store/heroes";
</script>

<h2>Top Heroes</h2>
<div class="dashboard-heroes">
  {#each heroesStore.topHeroes as hero}
    <DashboardHero {hero} />
  {/each}
</div>
