// react-hereoes/src/App.tsx
import { Link, Routes, Route, useLocation } from "react-router-dom";
import Dashboard from "./views/Dashboard";
import Hero from "./views/Hero";
import HeroesList from "./views/HeroesList";

const routes = [
  { path: "/", label: "Dashboard" },
  { path: "/heroes", label: "Heroes" },
];

export default function () {
  const location = useLocation();

  const routesCmp = routes.map((route) => {
    return (
      <li key={route.path}>
        <Link
          to={route.path}
          className={location.pathname === route.path ? "active" : undefined}
        >
          {route.label}
        </Link>
      </li>
    );
  });

  return (
    <main id="app-container">
      <h1>Tour of Heroes</h1>
      <ul id="navbar">{routesCmp}</ul>

      <Routes>
        <Route path="/" element={<Dashboard />} />
        <Route path="/heroes" element={<HeroesList />} />
        <Route path="/hero/:id" element={<Hero />} />
      </Routes>
    </main>
  );
}

// svelte-heroes/src/App.svelte
<script lang="ts">
  import { Router, Route, Link } from "svelte-navigator";

  const routes = [
    { path: "/", label: "Dashboard" },
    { path: "/heroes", label: "Heroes" },
  ];

  let active: string;

  import Dashboard from "./pages/Dashboard/Dashboard.svelte";
  import Hero from "./pages/Hero.svelte";
  import HeroesList from "./pages/List/HeroesList.svelte";
</script>

<Router>
  <main id="app-container">
    <h1>Tour of Heroes</h1>
    <ul id="navbar">
      {#each routes as route}
        <li>
          <Link
            class={active === route.path ? "active" : undefined}
            to={route.path}
            getProps={(props) => {
              const { isCurrent, location } = props;
              if (isCurrent) {
                active = location.pathname;
              }
              return props;
            }}
          >
            {route.label}
          </Link>
        </li>
      {/each}
    </ul>

    <Route path="/">
      <Dashboard />
    </Route>

    <Route path="/heroes">
      <HeroesList />
    </Route>

    <Route path="/hero/:id">
      <Hero />
    </Route>
  </main>
</Router>
