// react-hereoes/src/views/Hero.tsx
import { useParams, useNavigate } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { AppStateModel } from "../store";
import { updateHero } from "../store/heroes";
import TfInput from "../components/TfInput";
import { useState } from "react";

export default function () {
  const params = useParams();
  const navigate = useNavigate();
  const dispatch = useDispatch();

  const hero = useSelector((s: AppStateModel) => {
    const id = +params.id!;
    return s.heroes.heroes.find((h) => h.id === id);
  });

  const [name, setName] = useState<string>(hero?.name ?? "");

  if (!hero) {
    return (
      <div>
        <h2>Hero was not found</h2>
      </div>
    );
  }

  return (
    <div>
      <h2>{name} Details!</h2>

      <TfInput label="ID" value={hero.id.toString()} disabled />
      <TfInput label="Name" value={name} input={setName} />

      <button
        disabled={!name}
        onClick={() => {
          dispatch(updateHero(hero.id, name));
          navigate(-1);
        }}
        className="back-btn"
      >
        Back
      </button>
    </div>
  );
}

// svelte-heroes/src/pages/Hero.svelte
<script lang="ts">
  import heroesStore, { Hero } from "../store/heroes";
  import { useParams, useNavigate } from "svelte-navigator";
  import { get } from "svelte/store";
  import TfInput from "../components/TfInput.svelte";

  const params = useParams();
  const navigate = useNavigate();
  let hero: Hero;

  $: {
    const id = +get(params).id;
    hero = heroesStore.heroes.find((h) => h.id === id);
  }
</script>

{#if hero}
  <div>
    <h2>{hero.name} Details!</h2>

    <TfInput value={hero.id.toString()} disabled>ID</TfInput>
    <TfInput bind:value={hero.name}>Name</TfInput>

    <button
      disabled={!hero.name}
      on:click={() => {
        heroesStore.updateHero(hero.id, hero.name);
        navigate(-1);
      }}
      class="back-btn"
    >
      Back
    </button>
  </div>
{:else}
  <div>
    <h2>Hero was not found</h2>
  </div>
{/if}
