// react-hereoes/src/views/Hero.tsx
import { useParams, useNavigate } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { AppStateModel } from "../store";
import { updateHero } from "../store/heroes";
import TfInput from "../components/TfInput";
import { useState } from "react";

export default function () {
  const params = useParams();
  const navigate = useNavigate();
  const dispatch = useDispatch();

  const hero = useSelector((s: AppStateModel) => {
    const id = +params.id!;
    return s.heroes.heroes.find((h) => h.id === id);
  });

  const [name, setName] = useState<string>(hero?.name ?? "");

  if (!hero) {
    return (
      <div>
        <h2>Hero was not found</h2>
      </div>
    );
  }

  return (
    <div>
      <h2>{name} Details!</h2>

      <TfInput label="ID" value={hero.id.toString()} disabled />
      <TfInput label="Name" value={name} input={setName} />

      <button
        disabled={!name}
        onClick={() => {
          dispatch(updateHero(hero.id, name));
          navigate(-1);
        }}
        className="back-btn"
      >
        Back
      </button>
    </div>
  );
}

// ng-heroes/src/app/hero/hero.component.ts
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Store } from '@ngxs/store';
import { Hero, HeroesState, UpdateHero } from '@store/heroes';

@Component({
  selector: 'tf-hero',
  templateUrl: './hero.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeroComponent implements OnInit {
  hero?: Hero;

  constructor(
    private readonly route: ActivatedRoute,
    private readonly store: Store,
    private readonly router: Router
  ) {}

  public ngOnInit(): void {
    const params = this.route.snapshot.params as { id: string };
    const id = +params.id;

    this.hero = this.store.selectSnapshot(HeroesState.heroById)(id);
  }

  back() {
    const { id, name } = this.hero!;
    this.store.dispatch(new UpdateHero(id, name));
    this.router.navigateByUrl('/');
  }
}

<div *ngIf="hero">
  <h2>{{ hero.name }} Details!</h2>

  <div>
    <label>ID</label>
    <br />
    <input type="text" readonly [value]="hero.id" />
  </div>

  <div>
    <label>Name</label>
    <br />
    <input type="text" [(ngModel)]="hero.name" />
  </div>

  <button [disabled]="!hero.name" (click)="back()">Back</button>
</div>

<div *ngIf="!hero">
  <h2>Hero was not found</h2>
</div>
