// react-hereoes/src/components/DashboardHero.tsx
import { Hero } from "../store/heroes";
import { useNavigate } from "react-router-dom";

interface Props {
  hero: Hero;
}

export default function ({ hero }: Props) {
  const navigate = useNavigate();

  return (
    <div
      className="dashboard-hero"
      onClick={() => navigate("/hero/" + hero.id)}
    >
      <div>{hero.name}</div>
    </div>
  );
}

// vue-heroes/src/components/DashboardHero.vue
<template>
  <div class="dashboard-hero" @click="$router.push('/hero/' + hero.id)">
    <div>{{ hero.name }}</div>
  </div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from "vue-property-decorator";
import { Hero } from "../store";

@Component({
  name: "DashboardHero",
})
export default class DashboardHero extends Vue {
  @Prop({ required: true }) public hero!: Hero;
}
</script>
