// ng-heroes/src/app/heroes-list/list-hero/list-hero.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { Hero } from '@store/heroes';

@Component({
  selector: 'tf-list-hero',
  templateUrl: './list-hero.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ListHeroComponent {
  @Input() hero!: Hero;
}

<div class="list-hero">
  <span>{{ hero.id }}</span>
  <p>{{ hero.name }}</p>
</div>

// svelte-heroes/src/pages/List/ListHero.svelte
<script lang="ts">
  import type { Hero } from "../../store/heroes";
  import { useNavigate } from "svelte-navigator";

  export let hero: Hero;
  const navigate = useNavigate();
</script>

<div class="list-hero" on:click={() => navigate("/hero/" + hero.id)}>
  <span>{hero.id}</span>
  <p>{hero.name}</p>
</div>
