// ng-heroes/src/app/heroes-dashboard/dashboard-hero/dashboard-hero.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { Hero } from '@store/heroes';

@Component({
  selector: 'tf-dashboard-hero',
  host: {
    class: 'dashboard-hero',
  },
  template: ` <div>{{ hero.name }}</div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DashboardHeroComponent {
  @Input() hero!: Hero;
}

// react-hereoes/src/components/DashboardHero.tsx
import { Hero } from "../store/heroes";
import { useNavigate } from "react-router-dom";

interface Props {
  hero: Hero;
}

export default function ({ hero }: Props) {
  const navigate = useNavigate();

  return (
    <div
      className="dashboard-hero"
      onClick={() => navigate("/hero/" + hero.id)}
    >
      <div>{hero.name}</div>
    </div>
  );
}
