// svelte-heroes/src/pages/List/ListHero.svelte
<script lang="ts">
  import type { Hero } from "../../store/heroes";
  import { useNavigate } from "svelte-navigator";

  export let hero: Hero;
  const navigate = useNavigate();
</script>

<div class="list-hero" on:click={() => navigate("/hero/" + hero.id)}>
  <span>{hero.id}</span>
  <p>{hero.name}</p>
</div>

// react-hereoes/src/components/ListHero.tsx
import { useNavigate } from "react-router-dom";
import { Hero } from "../store/heroes";

interface Props {
  hero: Hero;
}

export default function ({ hero }: Props) {
  const navigate = useNavigate();

  return (
    <div className="list-hero" onClick={() => navigate("/hero/" + hero.id)}>
      <span>{hero.id}</span>
      <p>{hero.name}</p>
    </div>
  );
}
