// vue-heroes/src/components/ListHero.vue
<template>
  <dir>
    <div class="list-hero" @click="$router.push('/hero/' + hero.id)">
      <span>{{ hero.id }}</span>
      <p>{{ hero.name }}</p>
    </div>
  </dir>
</template>

<script lang="ts">
import { Vue, Component, Prop } from "vue-property-decorator";
import { Hero } from "../store";

@Component({
  name: "ListHero",
})
export default class ListHero extends Vue {
  @Prop({ required: true }) public hero!: Hero;
}
</script>

// react-hereoes/src/components/ListHero.tsx
import { useNavigate } from "react-router-dom";
import { Hero } from "../store/heroes";

interface Props {
  hero: Hero;
}

export default function ({ hero }: Props) {
  const navigate = useNavigate();

  return (
    <div className="list-hero" onClick={() => navigate("/hero/" + hero.id)}>
      <span>{hero.id}</span>
      <p>{hero.name}</p>
    </div>
  );
}
